// <auto-generated />
namespace br.com.klinderrh.social.infra.data.entityframework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Enums2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Enums2));
        
        string IMigrationMetadata.Id
        {
            get { return "201604041514049_Enums2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
